name: Unity Build


on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Cache
        uses: actions/cache@v3
        with:
          path: path/to/your/project/Library
          key: Library-MyProjectName-TargetPlatform
          restore-keys: |
            Library-DemoFPS-
            Library-
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Unity - Builder
        uses: game-ci/unity-builder@v4.1.1
        env:
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
          UNITY_SERIAL: ${{ secrets.UNITY_SERIAL }}
        with:
          targetPlatform: WebGL
      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: Build
          path: build
