name: Unity Build


on:
  push:
    branches:
      - main

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout ⬇️ # Grab our repo
        uses: actions/checkout@v2
      
      - name: Cache Library 📝 # We cache the library folder so that way it takes less time to run in subsequent builds
        uses: actions/cache@v3
        with:
          path: Library
          key: Library
          restore-keys: Library

      - name: Build To WebGL 🛠️ # Use the Unity Builder action to build to WebGL
        uses: game-ci/unity-builder@v2
        env:
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
          UNITY_SERIAL: ${{ secrets.UNITY_SERIAL }}
        with:
          targetPlatform: WebGL
          unityVersion: 2020.3.12f1 # Replace with your unity version (find it in ProjectSettings/ProjectVersion.txt)
          allowDirtyBuild: true # Uncomment if you want to force the build

      - name: Deploy To Pages 🚀 # Deploy the build to GitHub pages
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: gh-pages 
          folder: build/WebGL/WebGL
